package Vista;

import Modelo.ReporteViajes;
import javax.swing.*;
import java.awt.*;
import java.io.File;

public class ReportesVista extends JFrame {

    private JButton btnGenerar, btnVolver;
    private JLabel lblTitulo, lblInfo;
    private JPanel mainPanel, buttonPanel;

    public ReportesVista() {
        initComponentss();
        this.setLocationRelativeTo(null);
    }

    private void initComponentss() {
        setTitle("Reportes de Viajes - Airlink");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(600, 400);
        setResizable(false);

        mainPanel = new JPanel();
        mainPanel.setBackground(new Color(35, 22, 81));
        mainPanel.setLayout(new BorderLayout(10, 10));

        // ====== TÍTULO ======
        lblTitulo = new JLabel("Generar Reporte de Viajes", SwingConstants.CENTER);
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 22));
        lblTitulo.setForeground(Color.WHITE);
        lblTitulo.setBorder(BorderFactory.createEmptyBorder(30, 0, 20, 0));
        mainPanel.add(lblTitulo, BorderLayout.NORTH);

        // ====== INFO ======
        lblInfo = new JLabel("<html><div style='text-align:center;'>El sistema generará un reporte PDF con todos los viajes registrados.<br>"
                + "El archivo se guardará en tu carpeta Documentos.</div></html>", SwingConstants.CENTER);
        lblInfo.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblInfo.setForeground(Color.LIGHT_GRAY);
        mainPanel.add(lblInfo, BorderLayout.CENTER);

        // ====== BOTONES ======
        buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 30, 20));
        buttonPanel.setOpaque(false);

        btnGenerar = new JButton("Generar Reporte");
        btnGenerar.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnGenerar.setBackground(Color.WHITE);
        btnGenerar.setForeground(new Color(35, 22, 81));
        btnGenerar.setPreferredSize(new Dimension(180, 40));
        btnGenerar.addActionListener(e -> generarReporte());

        btnVolver = new JButton("Volver");
        btnVolver.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnVolver.setBackground(Color.WHITE);
        btnVolver.setForeground(new Color(35, 22, 81));
        btnVolver.setPreferredSize(new Dimension(120, 40));
        btnVolver.addActionListener(e -> volverMenu());

        buttonPanel.add(btnGenerar);
        buttonPanel.add(btnVolver);

        mainPanel.add(buttonPanel, BorderLayout.SOUTH);

        add(mainPanel);
    }

    private void generarReporte() {
        try {
            String ruta = System.getProperty("user.home") + File.separator + "Documents" + File.separator + "reporte_viajes.pdf";
            ReporteViajes reporte = new ReporteViajes();
            reporte.generarPDF(ruta);

            JOptionPane.showMessageDialog(this,
                    "📄 Reporte generado correctamente:\n" + ruta,
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "❌ Error al generar el reporte: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void volverMenu() {
        new MenuAdminModern().setVisible(true);
        this.dispose();
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new ReportesVista().setVisible(true));
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
